# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Multiple Jobs in a Pipeline

on:
  push:
    branches: [ main ]
 
jobs:

   one:
    runs-on: ubuntu-latest

    steps:
  #Checkout the code
    - name: Step-1 Checkout the Code
      uses: actions/checkout@v2
    
  #Build with Maven Goals
    - name: Step-2 Build with Maven
      run: mvn clean install
   
 
