# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Multiple Jobs in a Pipeline

on:
  push:
    branches: [ main ]
 
jobs:

   Build_Deploy:
    runs-on: AEP

    steps:
    
  #Checkout the code
    - name: Step-1 Checkout the Code
      uses: actions/checkout@v2.4.2
    
  #Build with Maven Goals
    - name: Step-2 Build with Maven
      run: mvn clean install
      


   Upload_to_Remote:
   
    runs-on: ubuntu-latest
    needs: Build_Deploy
    
    steps:
   
   #Checkout the code
     - name: Step-1 Checkout the code
       uses: actions/checkout@v2
       
  #Build with maven
     - name: Step-2 Build with maven
       run: 
            mvn clean;
            mvn install;

       
       
       
      
 
